# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    container_name: DockerBDD
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data

  application:
    build: .
    container_name: TheComputerClubBlog
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  dbdata: {}