# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.

version: '3.8'

services:
  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER}
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  application:
    build: .
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ROCKET_ADDRESS: 0.0.0.0

volumes:
  dbdata: {}