# Définir cette configuration Compose afin de lancer l'application
# Make Me Watch en production.
version: '3'
services:
  # Service du serveur
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://localhost:3000

  # Service du client
  client:
  # Configurations spécifiques au client
   build:
     context: ./client
     dockerfile: Dockerfile
   ports:
     - "80:4173"
  
   
