# Définir cette configuration Compose afin de lancer l'application
# Grilli en production.
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./private/grilli.com.conf:/etc/nginx/conf.d/default.conf
      - correspondance:/var/www/html
      
  php:
    build: .
    volumes:
      - correspondance:/var/www/html
    ports:
      - "9000:9000"

volumes:
  correspondance:
    
